steps:
- name: "gcr.io/cloud-builders/gradle"
  args: ["build"]
- name: "gcr.io/cloud-builders/gradle"
  args: ["javadoc"]
- name: "gcr.io/cloud-builders/gradle"
  args: ["appengineDeploy", "--stacktrace"]
timeout: "1600s"